use IDH_DWH;
CREATE TABLE dbo.D_TIME_OF_DAY
   	(
   	TIME_OF_DAY_RK int NOT NULL IDENTITY (1, 1),
   	Time_from time(3) NOT NULL,
   	Time_to time(3) NOT NULL,
   	Time_of_day varchar(MAX) NOT NULL
   	)  ON [PRIMARY]
   	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.D_TIME_OF_DAY ADD CONSTRAINT
   	PK_D_TIME_OF_DAY PRIMARY KEY CLUSTERED
   	(
   	TIME_OF_DAY_RK
   	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
 
GO